using System.Net;
using System.Net.Mail;
using System.Threading.Tasks;
using AIPMS.Application.Features.Notifications.Abstractions;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace AIPMS.Infrastructure.Email;

internal sealed class SmtpNotificationEmailSender(IOptions<EmailSettings> options,
    ILogger<SmtpNotificationEmailSender> logger) : INotificationEmailSender
{
    private readonly EmailSettings settings = options.Value;

    public async Task<bool> TrySendAsync(NotificationEmailDelivery delivery, CancellationToken ct)
    {
        if (!settings.IsConfigured)
        {
            logger.LogWarning("Notification email is queued because SMTP is not configured for {RecipientDomain}.", Domain(delivery.Email));
            return false;
        }
        try
        {
            using var message = new MailMessage
            {
                From = new MailAddress(settings.SenderAddress, settings.SenderName),
                Subject = delivery.Subject,
                Body = $"Hello {delivery.RecipientName},\n\n{delivery.Body}\n\nThis message was generated by AI-PMS.",
                IsBodyHtml = false
            };
            message.To.Add(new MailAddress(delivery.Email, delivery.RecipientName));
            using var client = new SmtpClient(settings.Host, settings.Port) { EnableSsl = settings.EnableSsl };
            if (!string.IsNullOrWhiteSpace(settings.Username)) client.Credentials = new NetworkCredential(settings.Username, settings.Password);
            await client.SendMailAsync(message, ct);
            return true;
        }
        catch (Exception ex) when (ex is SmtpException or InvalidOperationException or FormatException)
        {
            logger.LogWarning(ex, "Notification email delivery failed for {RecipientDomain}.", Domain(delivery.Email));
            return false;
        }
    }

    private static string Domain(string email)
    {
        var at = email.LastIndexOf('@');
        return at >= 0 ? email[(at + 1)..] : "unknown";
    }
}
