SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET XACT_ABORT ON;
BEGIN TRANSACTION;
IF COL_LENGTH('dbo.users', 'curriculum_code') IS NULL
    ALTER TABLE dbo.users ADD curriculum_code NVARCHAR(100) NULL;
COMMIT;
GO
