"""Opt-in provider smoke: create/delete one isolated room; never create an academic meeting."""
import argparse
import base64
import hashlib
import hmac
import json
import re
from pathlib import Path
import time
import urllib.error
import urllib.parse
import urllib.request
import uuid


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", type=Path, required=True)
    parser.add_argument("--execute", action="store_true")
    parser.add_argument("--cleanup-room", help="Retry cleanup of a previous vm-webhook-smoke-<32 hex> room only")
    args = parser.parse_args()
    if not args.execute:
        parser.error("Pass --execute to create/delete a real test room and trigger configured webhooks.")
    settings = json.loads(args.config.read_text(encoding="utf-8"))["VideoMeeting"]
    server = urllib.parse.urlsplit(settings["ServerUrl"])
    if server.scheme not in ("https", "wss") or not server.hostname or server.username or server.password:
        raise SystemExit("Invalid configured provider URL.")
    base = urllib.parse.urlunsplit(("https", server.netloc, "", "", ""))
    if args.cleanup_room and not re.fullmatch(r"vm-webhook-smoke-[0-9a-f]{32}", args.cleanup_room):
        parser.error("Cleanup accepts only an isolated smoke room name.")
    room = args.cleanup_room or "vm-webhook-smoke-" + uuid.uuid4().hex

    def b64(data):
        return base64.urlsafe_b64encode(data).rstrip(b"=").decode("ascii")

    def call(method, body, grant):
        now = int(time.time())
        claims = {"iss": settings["ApiKey"], "nbf": now - 5, "exp": now + 60, "video": grant}
        signing = b64(b'{"alg":"HS256","typ":"JWT"}') + "." + b64(json.dumps(claims).encode())
        signature = hmac.new(settings["ApiSecret"].encode(), signing.encode(), hashlib.sha256).digest()
        request = urllib.request.Request(base + "/twirp/livekit.RoomService/" + method,
                                         data=json.dumps(body).encode(), method="POST",
                                         headers={"Authorization": "Bearer " + signing + "." + b64(signature),
                                                  "Content-Type": "application/json"})
        try:
            with urllib.request.urlopen(request, timeout=20) as response:
                return json.load(response)
        except urllib.error.HTTPError as error:
            if method == "DeleteRoom" and error.code == 404:
                return {}
            raise RuntimeError(f"{method}: HTTP {error.code}") from None
        except (urllib.error.URLError, TimeoutError):
            raise RuntimeError(f"{method}: provider unavailable or timed out") from None

    print(json.dumps({"room": room, "started_unix": int(time.time())}), flush=True)
    try:
        if not args.cleanup_room:
            created = call("CreateRoom", {"name": room, "empty_timeout": 60, "max_participants": 2}, {"roomCreate": True})
            print(json.dumps({"created": True, "room_sid": created.get("sid")}), flush=True)
            time.sleep(3)
    finally:
        # Cleanup is limited to the unique room generated by this run, including ambiguous timeouts.
        call("DeleteRoom", {"room": room}, {"roomCreate": True})
        print(json.dumps({"delete_requested": True}), flush=True)
    remaining = call("ListRooms", {"names": [room]}, {"roomList": True}).get("rooms", [])
    if remaining:
        raise SystemExit("Test room still exists; inspect provider cleanup before retrying.")
    print(json.dumps({"cleanup_verified": True, "finished_unix": int(time.time())}), flush=True)


if __name__ == "__main__":
    main()
