<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AIPMS.Application\AIPMS.Application.csproj" />
    <ProjectReference Include="..\AIPMS.Infrastructure\AIPMS.Infrastructure.csproj" />
    <ProjectReference Include="..\AIPMS.AI\AIPMS.AI.csproj" />
  </ItemGroup>

</Project>
