using System;using System.Linq;using System.Threading;using System.Threading.Tasks;using AIPMS.Application.Common.Models;using AIPMS.Application.Features.Evaluations.Abstractions;using AIPMS.Application.Features.Evaluations.DTOs;using AIPMS.Infrastructure.Persistence.Generated;using Microsoft.EntityFrameworkCore;using M=AIPMS.Infrastructure.Persistence.Generated.Models;
namespace AIPMS.Infrastructure.Persistence.Repositories;
public sealed class EvaluationRepository(AipmsDbContext db):IEvaluationRepository
{
 public Task<bool> ProjectExistsAsync(long p,CancellationToken ct)=>db.Projects.AnyAsync(x=>x.Id==p,ct);
 public async Task<bool> CanEvaluateProjectAsync(long u,long p,CancellationToken ct)=>await db.SupervisorAssignments.AnyAsync(x=>x.ProjectId==p&&x.EndedAt==null&&x.SupervisorProfile.UserId==u,ct)||await db.Evaluations.AnyAsync(x=>x.ProjectId==p&&x.EvaluatorId==u,ct);
 public async Task<long> CreateDraftAsync(long p,long u,string t,CancellationToken ct){var e=new M.Evaluation{ProjectId=p,EvaluatorId=u,EvaluationType=t,Status="DRAFT",CreatedAt=DateTime.UtcNow,UpdatedAt=DateTime.UtcNow};db.Evaluations.Add(e);await db.SaveChangesAsync(ct);return e.Id;}
 public async Task<EvaluationDetailDto?> GetAsync(long id,CancellationToken ct){var e=await db.Evaluations.AsNoTracking().Include(x=>x.EvaluationDetails).FirstOrDefaultAsync(x=>x.Id==id,ct);if(e==null)return null;var criteria=await db.EvaluationCriteria.AsNoTracking().Where(x=>x.IsActive).OrderBy(x=>x.Id).ToListAsync(ct);return new(ToDto(e),criteria.Select(c=>{var d=e.EvaluationDetails.SingleOrDefault(x=>x.CriterionId==c.Id);return new EvaluationScoreDto(c.Id,c.Code,c.Name,c.WeightPercent,c.MaxScore,d?.Score,d?.Comments);}).ToList());}
 public async Task<PagedResult<EvaluationDto>> GetByProjectAsync(long p,int page,int size,CancellationToken ct){page=Math.Max(1,page);size=Math.Clamp(size,1,100);var q=db.Evaluations.AsNoTracking().Where(x=>x.ProjectId==p).OrderByDescending(x=>x.Id);var total=await q.CountAsync(ct);var items=(await q.Skip((page-1)*size).Take(size).ToListAsync(ct)).Select(ToDto).ToList();return new(items,page,size,total);}
 public async Task UpsertScoreAsync(long e,long c,decimal score,string? comments,CancellationToken ct){var d=await db.EvaluationDetails.SingleOrDefaultAsync(x=>x.EvaluationId==e&&x.CriterionId==c,ct);if(d==null){d=new(){EvaluationId=e,CriterionId=c,Score=score,Comments=comments,CreatedAt=DateTime.UtcNow,UpdatedAt=DateTime.UtcNow};db.EvaluationDetails.Add(d);}else{d.Score=score;d.Comments=comments;d.UpdatedAt=DateTime.UtcNow;}await db.SaveChangesAsync(ct);}
 public async Task UpdateCommentsAsync(long id,string? comments,CancellationToken ct){var e=await db.Evaluations.FindAsync([id],ct)??throw new InvalidOperationException();e.Comments=comments;e.UpdatedAt=DateTime.UtcNow;await db.SaveChangesAsync(ct);}
 public async Task<bool> FinalizeAsync(long id,decimal total,DateTime at,CancellationToken ct){var affected=await db.Evaluations.Where(x=>x.Id==id&&x.Status=="DRAFT").ExecuteUpdateAsync(s=>s.SetProperty(x=>x.Status,"FINALIZED").SetProperty(x=>x.TotalScore,total).SetProperty(x=>x.EvaluatedAt,at).SetProperty(x=>x.UpdatedAt,at),ct);return affected==1;}
 private static EvaluationDto ToDto(M.Evaluation e)=>new(e.Id,e.ProjectId,e.EvaluatorId,e.EvaluationType,e.Status,e.TotalScore,e.Comments,e.EvaluatedAt);
}
